### ISSUE TITLE
Es wird keine gültige Audio Datei mehr erzeugt

### ISSUE THREAD

**Issue by fisart** [Nall-chan/IPSVoiceRSS#1]
Ich habe seit einiger Zeit das Modul unter Windows im Einsatz ohne das es zu Problemen kommt. 
Ich habe nunmehr einmal unter Windows und dann mit einem Raspberry die identische Installation  durchgeführt bzw. wiederholt. Die Audio Datei (z.B. MP3 44KHZ Stereo) lässt sich nicht abspielen (Z.B.  mit Sonos : The song is not encoded correctly) Egal wie gross der Text ist, die Audio Datei hat immer 36 Bytes. Das funktionierende Modul habe ich seit einem Jahr oder so nicht mehr upgedated. Jetzt ist mir aufgefallen das seit einigen Tagen eine neue Version auf Github steht und ich vermute das sich hier ein Fehler eingeschlichen hat. Da ich meine funktionierende Installation nicht gefährden will habe ich auf den ultimativen Test (update des Moduls) verzichtet

**Comment by Nall-chan** [comment]
Kein Fehler.
ApiKey war nicht korrekt.
